language: python
sudo: false
python:
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade --only-binary numpy,scipy numpy scipy coveralls sphinx
script:
  - PYTHONPATH="$PWD" make coverage
after_success:
  - coveralls
# vim: ts=2:sts=2:sw=2:et
